title:  'FC Friedrichshafen e.V.'
description:  'Dein Verein im Osten der Stadt!'
email:  'verein@fc-friedrichshafen.de'
telephone:  '+49 171 3805124'
logo: '/assets/img/fc-friedrichshafen-logo.svg'
logo-with-text-white: '/assets/img/fc-friedrichshafen-logo-with-text-white.webp'
location:
  "@type":  'Place'
  address:  'Steinbeisstraße 10\n88046 Friedrichshafen'
  latitude: '47.65526696226333'
  longitude:  '9.499899713591837'
inLanguage: 'de'
twitter-username: 'fcfriedrichshfn'
facebook-username:  'fcfriedrichshafen'
instagram-username: 'fcfriedrichshafen'
author: 'chrstaud'
